### ISSUE TITLE
jsonPaginate() pulls fields from the pivot table when used on relationship

### ISSUE THREAD

**Issue by bjhijmans** [spatie/laravel-json-api-paginate#45]
I have 2 models called User and Client and a relationship on Client declared as follows:
```
public users()
{
    $this->belongsToMany(User::class)->withTimestamps();
}
```

When I call `$client->users()->jsonPaginate()`, the categories are returned, but the 'updated_at' and 'created_at' fields returned are from the pivot instead of the categories table. When I call `->paginate()` instead, the correct values are returned. From the sql log it seems like the pivot fields are usually aliased, but not when calling `jsonPaginate()`.

The query for jsonPaginate:
```
select *
from `users`
         inner join `client_user` on `users`.`id` = `client_user`.`user_id`
where `client_user`.`client_id` = ?
limit 30 offset 0
```
The query for paginate:
```
select `users`.*,
       `client_user`.`client_id`  as `pivot_client_id`,
       `client_user`.`user_id`    as `pivot_user_id`,
       `client_user`.`created_at` as `pivot_created_at`,
       `client_user`.`updated_at` as `pivot_updated_at`
from `users`
         inner join `client_user` on `users`.`id` = `client_user`.`user_id`
where `client_user`.`client_id` = ?
limit 15 offset 0
```

I would expect them to be identical.

**Comment by faustbrian** [comment]
Just ran into this too but it's a weird issue because if you add `dd($this->first()->toArray());` after https://github.com/spatie/laravel-json-api-paginate/blob/master/src/JsonApiPaginateServiceProvider.php#L29 you will already get messed up results, which happens before the actual pagination method is called.

**Comment by faustbrian** [comment]
@Zoefschildpad https://github.com/spatie/laravel-json-api-paginate/pull/47 this should resolve the issue. Now all the data is retrieved using the correct pagination methods which build the correct queries.

**Comment by Alserda** [comment]
I'm facing a similar issue where the jsonPaginate function removes the (already loaded) relationships (BelongsToMany) on a model, while the pivot attributes are joined instead. This also breaks my API resources as methods like `->whenLoaded`.
Merge request #47 does solve this issue.

**Comment by write-programmer** [comment]
@Alserda @faustbrian Could any of you merge request #47? The error still occurs and also breaks API Resources for me.

**Comment by vovarpd** [comment]
I'm facing this issue too.
Pivot attributes have merged into the main Model. 
I would expect a 'pivot' array as I can see from simplePaginate/paginate methods.

Could anyone merge the #47 ?

**Comment by Alserda** [comment]
The maintainers seem to take a while to merge the request. A temporary work around can be to use @faustbrian's fork:

```lang-json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/faustbrian/laravel-json-api-paginate"
        }
    ],
    "require": {
        "spatie/laravel-json-api-paginate": "master",
    }
}
```

**Comment by freekmurze** [comment]
We'll continue this conversation in #47
